version: '3.6'
services:
    app:
        restart: always
        image: frutik777/k8s-example:latest
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - ${APP_PORT}:${APP_PORT}
        env_file:
            - .env