apiVersion: v1
kind: Service
metadata:
    name: demo-app
spec:
    ports:
        -   port: 80
            targetPort: 7777
            protocol: TCP
            name: http
    selector:
        app: demo-app